version: 0.2

phases:
  build:
    commands:
      - echo "CODEBUILD_SRC_DIR: $CODEBUILD_SRC_DIR"
      - ls -l $CODEBUILD_SRC_DIR
      - cd $CODEBUILD_SRC_DIR/SourceArtifact
      - pip install -r requirements.txt
      - zip -r application.zip * .ebextensions